package net.foulest.ospreyproxy;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import io.netty.util.ResourceLeakDetector;
import org.jspecify.annotations.NonNull;
import org.slf4j.LoggerFactory;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;
import tools.jackson.core.JacksonException;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;

/**
 * Handler for the GET /privacy endpoint.
 * <p>
 * Returns a live snapshot of the server's privacy-related configuration so
 * that anyone can verify at runtime, not just by reading source code,
 * that request logging, access logs, and data persistence are disabled.
 * <p>
 * Also exposes the Git commit hash and JAR SHA-256 checksum so that anyone
 * can clone the repo, build the same commit, and verify that the checksum
 * matches, proving the open source code is what's actually running.
 *
 * @author Foulest
 */
@Component
public class PrivacyHandler {

    private static final ObjectMapper MAPPER = JsonMapper.builder().build();

    // Build metadata loaded once at startup
    private static final String BUILD_COMMIT;
    private static final String BUILD_JAR_SHA256;

    static {
        // Load Git commit from build-info.properties (generated by Gradle)
        Properties buildInfo = new Properties();

        try (InputStream is = PrivacyHandler.class.getClassLoader().getResourceAsStream("build-info.properties")) {
            if (is != null) {
                buildInfo.load(is);
            }
        } catch (IOException ignored) {
        }

        BUILD_COMMIT = buildInfo.getProperty("ospreyproxy.build.commit", "unknown");

        // Self-hash: compute SHA-256 of the running JAR by locating it via the class's code source.
        // This avoids the chicken-and-egg problem of embedding a checksum inside the file it checksums.
        // Users can verify by running: sha256sum OspreyProxy.jar
        BUILD_JAR_SHA256 = computeOwnJarSha256();
    }

    /**
     * Handles GET /privacy requests.
     * Reads live JVM state to build the response - nothing is hardcoded.
     */
    @NonNull
    public Mono<ServerResponse> handlePrivacy(@NonNull ServerRequest request) {
        Map<String, Object> privacy = new LinkedHashMap<>();

        // Root log level (proves no per-request INFO/DEBUG output)
        privacy.put("rootLogLevel", getRootLogLevel());

        // Reactor Netty access log (records client IPs and URIs if enabled)
        privacy.put("reactorNettyAccessLog", getAccessLogEnabled());

        // Netty resource leak detector level (DISABLED means no tracking)
        privacy.put("nettyLeakDetection", ResourceLeakDetector.getLevel().name());

        // Whether a log file is configured (logging.file.name / logging.file.path)
        privacy.put("logFileConfigured", isLogFileConfigured());

        // Spring error detail suppression
        privacy.put("includeStacktrace", getSystemProperty("spring.web.error.include-stacktrace", "never"));
        privacy.put("includeMessage", getSystemProperty("spring.web.error.include-message", "never"));
        privacy.put("includeBindingErrors", getSystemProperty("spring.web.error.include-binding-errors", "never"));

        // Data persistence
        privacy.put("database", "none");
        privacy.put("diskWrites", false);

        // Build verification — clone the repo, build the same commit, compare the checksum.
        // If your checksum matches, the open source code is what's running on this server.
        privacy.put("buildCommit", BUILD_COMMIT);
        privacy.put("buildJarSha256", BUILD_JAR_SHA256);

        // Source code link for verification
        privacy.put("sourceCode", "https://github.com/OspreyProject/OspreyProxy");

        String body;

        try {
            body = MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(privacy);
        } catch (JacksonException e) {
            body = "{\"error\":\"Failed to serialize privacy info\"}";
        }

        return ServerResponse.ok()
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(body);
    }

    /**
     * Reads the root logger level from Logback at runtime.
     */
    private static @NonNull String getRootLogLevel() {
        try {
            LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
            Logger root = context.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME);
            Level level = root.getLevel();
            return level != null ? level.toString() : "UNKNOWN";
        } catch (ClassCastException e) {
            return "UNKNOWN";
        }
    }

    /**
     * Checks the live system property for Reactor Netty access log.
     */
    private static boolean getAccessLogEnabled() {
        return Boolean.parseBoolean(
                System.getProperty("reactor.netty.http.server.accessLogEnabled", "false")
        );
    }

    /**
     * Checks whether a log file path is configured via system properties.
     */
    private static boolean isLogFileConfigured() {
        String fileName = System.getProperty("logging.file.name");
        String filePath = System.getProperty("logging.file.path");
        return (fileName != null && !fileName.isBlank())
                || (filePath != null && !filePath.isBlank());
    }

    /**
     * Reads a system property with a fallback default.
     */
    private static @NonNull String getSystemProperty(@NonNull String key, @NonNull String defaultValue) {
        return System.getProperty(key, defaultValue);
    }

    /**
     * Computes the SHA-256 checksum of the running JAR file.
     * Locates the JAR via this class's ProtectionDomain code source.
     * Returns "unknown" if not running from a JAR (e.g., during development via bootRun).
     */
    private static @NonNull String computeOwnJarSha256() {
        try {
            URL codeSourceUrl = PrivacyHandler.class.getProtectionDomain().getCodeSource().getLocation();
            URI uri = codeSourceUrl.toURI();

            // Handle nested JAR URLs from Spring Boot's fat JAR launcher (jar:file:/path/to/app.jar!/BOOT-INF/classes!/)
            String uriString = uri.toString();

            if (uriString.startsWith("jar:")) {
                // Extract the outer JAR path from jar:file:/path/to/app.jar!/...
                int separator = uriString.indexOf('!');

                if (separator > 0) {
                    uriString = uriString.substring(4, separator); // Remove "jar:" prefix and everything after "!"
                }

                uri = new URI(uriString);
            }

            Path jarPath = Paths.get(uri);

            if (!Files.isRegularFile(jarPath)) {
                return "unknown (not running from JAR)";
            }

            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] fileBytes = Files.readAllBytes(jarPath);
            byte[] hash = digest.digest(fileBytes);
            return HexFormat.of().formatHex(hash);
        } catch (URISyntaxException | IOException | NoSuchAlgorithmException | SecurityException e) {
            return "unknown";
        }
    }
}
