/*
 * OspreyProxy - backend code for our proxy server using Spring WebFlux.
 * Copyright (C) 2026 Osprey Project (https://github.com/OspreyProject)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package net.foulest.ospreyproxy;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import io.netty.util.ResourceLeakDetector;
import lombok.extern.slf4j.Slf4j;
import org.jetbrains.annotations.Contract;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;
import org.slf4j.LoggerFactory;
import org.springframework.core.env.Environment;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;
import tools.jackson.core.JacksonException;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.DigestInputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;

/**
 * Handler for the <a href="https://api.osprey.ac/privacy">GET /privacy</a> endpoint.
 * <p>
 * Returns a live snapshot of the server's privacy-related configuration so
 * that anyone can verify at runtime, not just by reading source code,
 * that request logging, access logs, and data persistence are disabled.
 * <p>
 * Also exposes the Git commit hash and JAR SHA-256 checksum so that anyone
 * can clone the repo, build the same commit, and verify that the checksum
 * matches, proving the open source code is what's actually running.
 */
@Slf4j
@Component
public class PrivacyHandler {

    private static final ObjectMapper MAPPER = JsonMapper.builder().build();
    private static final String BUILD_COMMIT;
    private static final String BUILD_JAR_SHA256;
    private final Environment environment;

    @Contract(pure = true)
    public PrivacyHandler(Environment environment) {
        this.environment = environment;
    }

    static {
        // Loads Git commit from build-info.properties (generated by Gradle)
        Properties buildInfo = new Properties();

        try (InputStream is = PrivacyHandler.class.getClassLoader().getResourceAsStream("build-info.properties")) {
            if (is != null) {
                buildInfo.load(is);
            }
        } catch (IOException e) {
            log.warn("Failed to load build info properties", e);
        }

        BUILD_COMMIT = buildInfo.getProperty("ospreyproxy.build.commit", "unknown");

        // Computes SHA-256 of the running JAR by locating it via the class's code source
        // Users can verify by running: sha256sum OspreyProxy.jar
        BUILD_JAR_SHA256 = computeOwnJarSha256();
    }

    /**
     * Handles GET /privacy requests.
     * Reads live JVM state and OS config files to build the response.
     */
    @NonNull
    public Mono<ServerResponse> handlePrivacy(@NonNull ServerRequest request) {
        Map<String, Object> privacy = new LinkedHashMap<>();

        // --- Application-level checks (read from running JVM) ---

        // Root log level: proves no per-request INFO/DEBUG output
        privacy.put("rootLogLevel", getRootLogLevel());

        // Whether any Logback file appenders are configured (would write logs to disk)
        privacy.put("logbackFileAppenders", getLogbackFileAppenderCount());

        // Reactor Netty access log: records client IPs and URIs if enabled
        privacy.put("reactorNettyAccessLog", getAccessLogEnabled());

        // Netty resource leak detector level: DISABLED means no tracking
        privacy.put("nettyLeakDetection", ResourceLeakDetector.getLevel().name());

        // Whether a Spring log file is configured (logging.file.name / logging.file.path)
        privacy.put("springLogFileConfigured", isLogFileConfigured());

        // Spring error detail suppression
        privacy.put("includeStacktrace", environment.getProperty("spring.web.error.include-stacktrace", "never"));
        privacy.put("includeMessage", getSystemProperty("spring.web.error.include-message", "never"));
        privacy.put("includeBindingErrors", getSystemProperty("spring.web.error.include-binding-errors", "never"));

        // Whether any database driver implementation is on the classpath.
        // Note: java.sql.DriverManager is part of the JDK itself, so we check
        // for actual driver implementations (H2, MySQL, PostgreSQL, etc.)
        privacy.put("databaseDriverOnClasspath", hasDatabaseDriver());

        // --- OS-level checks (read from config files on disk) ---

        // Nginx access log status: reads the actual Nginx config to verify access_log is off
        privacy.put("nginxAccessLog", getNginxAccessLogStatus());

        // Systemd journal persistence: reads journald.conf to verify Storage setting
        privacy.put("systemdJournalStorage", getJournaldStorage());

        // --- Build verification ---

        // Git commit hash and JAR SHA-256 for reproducible build verification
        privacy.put("buildCommit", BUILD_COMMIT);
        privacy.put("buildJarSha256", BUILD_JAR_SHA256);

        // Source code link for verification
        privacy.put("sourceCode", "https://github.com/OspreyProject/OspreyProxy");

        String body;

        try {
            body = MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(privacy);
        } catch (JacksonException e) {
            log.warn("Failed to serialize privacy info to JSON", e);
            body = "{\"error\":\"Failed to serialize privacy info\"}";
        }

        return ServerResponse.ok()
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(body);
    }

    /**
     * Reads the root logger level from Logback at runtime.
     */
    private static @NonNull String getRootLogLevel() {
        try {
            LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
            Logger root = context.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME);
            Level level = root.getLevel();
            return level != null ? level.toString() : "UNKNOWN";
        } catch (ClassCastException e) {
            log.warn("Failed to read Logback root logger level", e);
            return "UNKNOWN";
        }
    }

    /**
     * Checks the live system property for Reactor Netty access log.
     */
    private static boolean getAccessLogEnabled() {
        return Boolean.parseBoolean(
                System.getProperty("reactor.netty.http.server.accessLogEnabled", "false")
        );
    }

    /**
     * Checks whether a log file path is configured via system properties.
     */
    private static boolean isLogFileConfigured() {
        String fileName = System.getProperty("logging.file.name");
        String filePath = System.getProperty("logging.file.path");
        return (fileName != null && !fileName.isBlank())
                || (filePath != null && !filePath.isBlank());
    }

    /**
     * Reads a system property with a fallback default.
     */
    private static @NonNull String getSystemProperty(@NonNull String key, @NonNull String defaultValue) {
        return System.getProperty(key, defaultValue);
    }

    /**
     * Counts how many Logback file-based appenders are active.
     * If 0, no logs are being written to disk by the application.
     * <p>
     * Uses {@code getSimpleName().contains("File")} rather than {@code instanceof}
     * to avoid a compile-time dependency on Logback's internal API. This catches
     * FileAppender, RollingFileAppender, and future subclasses. A false positive
     * would only make the privacy report more conservative (reporting potential
     * disk logging), which is the safe direction for a privacy audit tool.
     */
    private static int getLogbackFileAppenderCount() {
        try {
            LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
            Logger root = context.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME);
            int count = 0;
            var it = root.iteratorForAppenders();

            while (it.hasNext()) {
                var appender = it.next();
                String name = appender.getClass().getSimpleName();

                // FileAppender, RollingFileAppender, etc.
                if (name.contains("File")) {
                    count++;
                }
            }
            return count;
        } catch (ClassCastException e) {
            log.warn("Failed to read Logback appenders", e);
            return -1; // Unable to determine
        }
    }

    /**
     * Reads Nginx config files to determine access_log status.
     * Scans all common config paths for access_log directives, including
     * those indented inside server/location blocks.
     * Returns the most relevant access_log status found.
     */
    @SuppressWarnings("NestedMethodCall")
    private static @NonNull String getNginxAccessLogStatus() {
        // Check site-specific config first, then the global config
        String[] configPaths = {
                "/etc/nginx/sites-enabled/ospreyproxy",
                "/etc/nginx/sites-available/ospreyproxy",
                "/etc/nginx/conf.d/ospreyproxy.conf",
                "/etc/nginx/nginx.conf"
        };

        // Track what we find across all config files
        String lastFound = null;
        boolean anyConfigReadable = false;

        for (String configPath : configPaths) {
            Path path = Paths.get(configPath);

            if (!Files.isReadable(path)) {
                continue;
            }

            anyConfigReadable = true;

            try {
                String content = Files.readString(path);

                // Search every line for access_log (handles indented directives in server/location blocks)
                for (String line : content.split("\n")) {
                    String trimmed = line.trim();

                    // Skip lines that don't start with "access_log"
                    if (trimmed.isEmpty() || trimmed.charAt(0) == '#' || !trimmed.startsWith("access_log")) {
                        continue;
                    }

                    // Extract the value after "access_log" (e.g., "off;", "/dev/null;")
                    // Nginx syntax: access_log <path|off> [format ...];
                    String value = trimmed.substring("access_log".length()).trim();

                    // Strip trailing semicolon and any format/params after the path
                    int space = value.indexOf(' ');
                    if (space > 0) {
                        value = value.substring(0, space);
                    }

                    // Strip trailing semicolon if present
                    if (!value.isEmpty() && value.charAt(value.length() - 1) == ';') {
                        value = value.substring(0, value.length() - 1);
                    }

                    // Check if access_log is set to "off" or a null device, which means disabled
                    // Site-specific "off" takes precedence, return immediately if found
                    if ("off".equals(value) || "/dev/null".equals(value)) {
                        return "disabled";
                    }

                    lastFound = trimmed;
                }
            } catch (IOException e) {
                log.warn("Failed to read Nginx config file", e);
            }
        }

        if (!anyConfigReadable) {
            return "config not found (not running on Linux or Nginx not installed)";
        }

        if (lastFound != null) {
            return "enabled (" + lastFound + ")";
        }
        return "not set (defaults to enabled)";
    }

    /**
     * Reads journald config to determine journal persistence.
     * "volatile" means journals are stored in /run/log/journal (RAM only, lost on reboot).
     * "persistent" or "auto" means journals may be written to /var/log/journal (disk).
     * Checks drop-in directories first (they override the main config).
     * <p>
     * When Storage=auto (the default), systemd only persists journals if
     * /var/log/journal/ exists. If that directory is absent, journals go
     * to /run/log/journal/ (RAM only, lost on reboot), effectively volatile.
     */
    private static @NonNull String getJournaldStorage() {
        // Drop-in configs override the main config, check them first
        String dropInResult = checkJournaldDropIns();

        if (dropInResult != null) {
            return resolveAutoStorage(dropInResult);
        }

        // Fall back to main config
        Path journaldConf = Paths.get("/etc/systemd/journald.conf");
        String result = parseJournaldStorage(journaldConf);

        if (result != null) {
            return resolveAutoStorage(result);
        }

        if (Files.isReadable(journaldConf)) {
            // No Storage= directive found (systemd defaults to "auto")
            return resolveAutoStorage("auto");
        }
        return "config not found (not running on Linux or systemd not installed)";
    }

    /**
     * If the storage mode is "auto", checks whether /var/log/journal/ exists
     * to determine the effective behavior. In auto mode, systemd persists
     * journals only if that directory exists; otherwise journals are volatile.
     */
    private static @NonNull String resolveAutoStorage(@NonNull String storageValue) {
        if ("auto".equals(storageValue)) {
            boolean persistDirExists = Files.isDirectory(Paths.get("/var/log/journal"));

            if (persistDirExists) {
                return "auto (persistent; /var/log/journal exists)";
            }
            return "auto (volatile; /var/log/journal does not exist)";
        }
        return storageValue;
    }

    /**
     * Checks /etc/systemd/journald.conf.d/*.conf for Storage= overrides.
     */
    private static @Nullable String checkJournaldDropIns() {
        Path dropInDir = Paths.get("/etc/systemd/journald.conf.d");

        if (!Files.isDirectory(dropInDir)) {
            return null;
        }

        try (var entries = Files.list(dropInDir)) {
            // Process in sorted order (last one wins in systemd)
            String lastValue = null;

            for (Path file : entries.sorted().toList()) {
                if (!file.toString().endsWith(".conf") || !Files.isReadable(file)) {
                    continue;
                }

                String parsed = parseJournaldStorage(file);

                if (parsed != null) {
                    lastValue = parsed;
                }
            }
            return lastValue;
        } catch (IOException e) {
            log.warn("Failed to read journald drop-in configs", e);
            return null;
        }
    }

    /**
     * Parses a journald config file for the Storage= directive.
     * Returns the value if found, or null if not present.
     */
    @SuppressWarnings("NestedMethodCall")
    private static @Nullable String parseJournaldStorage(@NonNull Path path) {
        if (!Files.isReadable(path)) {
            return null;
        }

        try {
            String content = Files.readString(path);

            for (String line : content.split("\n")) {
                String trimmed = line.trim();

                // Skip comments and blank lines
                if (trimmed.isEmpty() || trimmed.charAt(0) == '#') {
                    continue;
                }

                if (trimmed.startsWith("Storage=")) {
                    return trimmed.substring("Storage=".length()).trim().toLowerCase(Locale.ROOT);
                }
            }
        } catch (IOException e) {
            log.warn("Failed to read journald config file", e);
        }
        return null;
    }

    /**
     * Checks whether any database driver implementation is on the classpath.
     */
    private static boolean hasDatabaseDriver() {
        String[] driverClasses = {
                "org.h2.Driver",
                "com.mysql.cj.jdbc.Driver",
                "org.mariadb.jdbc.Driver",
                "org.postgresql.Driver",
                "oracle.jdbc.OracleDriver",
                "com.microsoft.sqlserver.jdbc.SQLServerDriver",
                "org.sqlite.JDBC",
                "com.mongodb.client.MongoClient"
        };

        ClassLoader cl = PrivacyHandler.class.getClassLoader();

        for (String driver : driverClasses) {
            try {
                Class.forName(driver, false, cl);
                return true;
            } catch (ClassNotFoundException ignored) {
            }
        }
        return false;
    }

    /**
     * Computes the SHA-256 checksum of the running JAR file.
     * Locates the JAR via this class's ProtectionDomain code source.
     * Returns "unknown" if not running from a JAR (e.g., during development via bootRun).
     * Uses streaming to avoid loading the entire fat JAR into memory at once.
     */
    private static @NonNull String computeOwnJarSha256() {
        try {
            URL codeSourceUrl = PrivacyHandler.class.getProtectionDomain().getCodeSource().getLocation();
            URI uri = codeSourceUrl.toURI();

            // Handle nested JAR URLs from Spring Boot's fat JAR launcher (jar:file:/path/to/app.jar!/BOOT-INF/classes!/)
            String uriString = uri.toString();

            if (uriString.startsWith("jar:")) {
                // Extract the outer JAR path from jar:file:/path/to/app.jar!/...
                int separator = uriString.indexOf('!');

                if (separator > 0) {
                    uriString = uriString.substring(4, separator); // Remove "jar:" prefix and everything after "!"
                }

                uri = new URI(uriString);
            }

            Path jarPath = Paths.get(uri);

            if (!Files.isRegularFile(jarPath)) {
                return "unknown (not running from JAR)";
            }

            // Stream the file through a DigestInputStream in 8 KB chunks to avoid
            // loading the entire fat JAR (potentially 30+ MB) into a single byte array.
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] buffer = new byte[8192];

            try (InputStream fis = Files.newInputStream(jarPath);
                 DigestInputStream dis = new DigestInputStream(fis, digest)) {
                // noinspection StatementWithEmptyBody
                while (dis.read(buffer) != -1) {
                    // DigestInputStream updates the digest automatically
                }
            }

            byte[] hash = digest.digest();
            return HexFormat.of().formatHex(hash);
        } catch (URISyntaxException | IOException | NoSuchAlgorithmException | SecurityException e) {
            log.warn("Failed to compute JAR SHA-256 checksum", e);
            return "unknown";
        }
    }
}
